import { useEffect, useState } from 'react';
import {Link} from 'react-router-dom';
import {sendCitizenLoginOtp, verifyCitizenLoginOtp} from '../../api/citizenAuth.api';
import {useAuth} from '../../context/AuthContext';
import Message from '../../components/Message';

export default function CitizenLogin(){
  const [step,setStep]=useState('email'); const [email,setEmail]=useState(''); const [otp,setOtp]=useState('');
  const [seconds,setSeconds]=useState(0); const [loading,setLoading]=useState(false); const [msg,setMsg]=useState(''); const [err,setErr]=useState(false); const {login}=useAuth();
  useEffect(()=>{if(!seconds)return;const t=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[seconds]);
  const request=async e=>{e.preventDefault();setLoading(true);setMsg('');setErr(false);try{await sendCitizenLoginOtp({email});setStep('otp');setSeconds(600);setMsg(`We sent a 6-digit verification code to ${email}`)}catch(e){setErr(true);setMsg(e.response?.data?.message||'Unable to send OTP.')}finally{setLoading(false)}};
  const verify=async e=>{e.preventDefault();setLoading(true);setMsg('');setErr(false);try{const r=await verifyCitizenLoginOtp({email,otp});login(r.data.data)}catch(e){setErr(true);setMsg(e.response?.data?.message||'Unable to verify OTP.')}finally{setLoading(false)}};
  const resend=async()=>{if(seconds>540)return;setLoading(true);setMsg('');setErr(false);try{await sendCitizenLoginOtp({email});setSeconds(600);setOtp('');setMsg(`A new verification code was sent to ${email}`)}catch(e){setErr(true);setMsg(e.response?.data?.message||'Unable to resend OTP.')}finally{setLoading(false)}};
  const minutes=Math.floor(seconds/60), remaining=String(seconds%60).padStart(2,'0');
  return <div className="auth-page"><section className="auth-visual"><Link className="brand" to="/citizen/login"><span className="brand-mark">⌂</span><span>SmartCity</span></Link><div className="auth-copy"><span className="eyebrow">Your city. Your voice.</span><h1>Make your neighborhood better.</h1><p>Report civic issues, follow progress, and stay connected with the people improving your city.</p></div><div className="city-grid">{Array.from({length:8},(_,i)=><span key={i}/>)}</div></section><section className="auth-form-side"><div className="auth-card"><Link className="brand" to="/citizen/login"><span className="brand-mark">⌂</span><span>SmartCity Portal</span></Link>{step==='email'?<><h2>Welcome back</h2><p className="subtitle">Enter your email and we'll send a secure one-time code. No password required.</p><form onSubmit={request}><div className="field"><label>Email address</label><input type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} required/></div><button className="primary-btn full" type="submit" disabled={loading}>{loading?'Sending code…':<>Send OTP <span>→</span></>}</button></form></>:<><div className="step-label"><span className="step-dot done">✓</span><span>Email entered</span><i className="done-line"/><span className="step-dot active">2</span><span>Verify</span></div><h2>Check your inbox</h2><p className="subtitle">Enter the 6-digit code sent to <strong>{email}</strong>.</p><form onSubmit={verify}><div className="otp-wrap"><label>Verification code</label><input className="otp-input" inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" placeholder="000000" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} required/></div><div className="otp-meta"><span>{seconds?`Code expires in ${minutes}:${remaining}`:'Code expired'}</span><button type="button" className="text-btn" onClick={resend} disabled={loading||seconds>540}>Resend code</button></div><button className="primary-btn full" type="submit" disabled={loading||otp.length!==6}>{loading?'Verifying…':<>Sign in <span>→</span></>}</button></form><button className="back-btn" type="button" onClick={()=>{setStep('email');setOtp('');setMsg('');setErr(false)}}>← Change email</button></>}<Message text={msg} error={err}/><div className="link-row">New to SmartCity? <Link to="/citizen/signup">Create a citizen account</Link><br/><span style={{display:'inline-block',marginTop:10}}>Staff member? <Link to="/admin/login">Admin sign in</Link></span></div></div></section></div>
}
